steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/todoapp-340315/todoappspl:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/todoapp-340315/todoappspl:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'todoappspl', '--image', 'gcr.io/todoapp-340315/todoappspl:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/todoapp-340315/todoappspl:$COMMIT_SHA'
